### ISSUE TITLE
It fails to import

### ISSUE THREAD

**Issue by OlegZee** [0rangeT1ger/React-form-validator#3]
`import ValidateableForm from 'react-form-validate';` causes failure on
```
import vForm from './source/ValidateableForm.react.jsx';

export default vForm;
module.exports = vForm;
```

Library seems not properly packaged.

**Comment by 0rangeT1ger** [comment]
Thanks for the feedback...
I didn't realize that before when I use it in my own project...
Fixed that now, try again?

**Comment by mesutyigit** [comment]
Problem not solved. I got same error.

**Comment by jothi-pyt** [comment]
Problem still exists. I got same error.

Am using React latest version v16.1.1
